apiVersion: skaffold/v2beta26
kind: Config
metadata:
  name: authentication-service

build:
  artifacts:
    - image: authentication-service
      context: .
      docker:
        dockerfile: Dockerfile

deploy:
  kubectl:
    manifests:
      - ./configuration/secrets.yaml
      - ./configuration/deployment.yaml
      - ./configuration/service.yaml
      - ./configuration/database.yaml
